name: CI Lint

on:
  push:
    branches:
      - 'master'
      - 'st3176'
    paths:
      - '**/*.json'
      - '**/*.py'
      - '**/*.sublime-*'
  pull_request:
    branches:
      - '**'
    paths:
      - '**/*.json'
      - '**/*.py'
      - '**/*.sublime-*'
  workflow_dispatch:

jobs:
  lint:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.13'
        arch:
          - 'x64'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.arch }}
      - name: Install linters
        run: pip install -r tests/requirements.txt
      - name: Run black
        run: python -m black --check .
